# Site settings
email: "joshkpete@gmail.com"
baseurl: ""
paginate: 10
paginate_path: "/blog/page-:num"
google_analytics: UA-88221227-1

# SEO settings
title: Josh Peterson
description: "Media Art"
url: "https://josh-peterson.com"
twitter_username: "joshypants"
default_img: "/assets/img/Josh-Peterson-dot-com.jpg"

# Profile settings
name: Josh Peterson
profile_img: /assets/img/Josh-Peterson-photo.jpg
profile: "Josh Peterson is an artist, web developer, and creative technologist based in NYC. Site-specific interactive art is his favorite art."
social:
  github: "https://github.com/joshkpeterson"
  twitter: "https://twitter.com/joshypants"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /blog/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
