# Site settings
email: "joshkpete@gmail.com"
baseurl: ""
paginate: 10
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Josh Peterson
description: "Media Art"
url: "https://josh-peterson.com"
twitter_username: "joshypants"
default_img: "https://placekitten.com/1000/1000"

# Profile settings
name: Josh Peterson
profile_img: 
profile: "Artist and Technologist based in NYC"
social:
  github: "https://github.com/joshkpeterson"
  twitter: "https://twitter.com/joshypants"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
